// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thirdparty/sofa/pbrpc/rpc_option.proto

package sofa.pbrpc;

public final class RpcOption {
  private RpcOption() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(serviceTimeout);
    registry.add(methodTimeout);
    registry.add(requestCompressType);
    registry.add(responseCompressType);
  }
  public enum CompressType
      implements com.google.protobuf.ProtocolMessageEnum {
    CompressTypeNone(0, 0),
    CompressTypeGzip(1, 1),
    CompressTypeZlib(2, 2),
    CompressTypeSnappy(3, 3),
    CompressTypeLZ4(4, 4),
    ;
    
    public static final int CompressTypeNone_VALUE = 0;
    public static final int CompressTypeGzip_VALUE = 1;
    public static final int CompressTypeZlib_VALUE = 2;
    public static final int CompressTypeSnappy_VALUE = 3;
    public static final int CompressTypeLZ4_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static CompressType valueOf(int value) {
      switch (value) {
        case 0: return CompressTypeNone;
        case 1: return CompressTypeGzip;
        case 2: return CompressTypeZlib;
        case 3: return CompressTypeSnappy;
        case 4: return CompressTypeLZ4;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CompressType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CompressType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CompressType>() {
            public CompressType findValueByNumber(int number) {
              return CompressType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sofa.pbrpc.RpcOption.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final CompressType[] VALUES = {
      CompressTypeNone, CompressTypeGzip, CompressTypeZlib, CompressTypeSnappy, CompressTypeLZ4, 
    };
    
    public static CompressType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CompressType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:sofa.pbrpc.CompressType)
  }
  
  public static final int SERVICE_TIMEOUT_FIELD_NUMBER = 20000;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.Long> serviceTimeout = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int METHOD_TIMEOUT_FIELD_NUMBER = 20000;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Long> methodTimeout = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int REQUEST_COMPRESS_TYPE_FIELD_NUMBER = 20001;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      sofa.pbrpc.RpcOption.CompressType> requestCompressType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        sofa.pbrpc.RpcOption.CompressType.class,
        null);
  public static final int RESPONSE_COMPRESS_TYPE_FIELD_NUMBER = 20002;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      sofa.pbrpc.RpcOption.CompressType> responseCompressType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        sofa.pbrpc.RpcOption.CompressType.class,
        null);
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&thirdparty/sofa/pbrpc/rpc_option.proto" +
      "\022\nsofa.pbrpc\032 google/protobuf/descriptor" +
      ".proto*}\n\014CompressType\022\024\n\020CompressTypeNo" +
      "ne\020\000\022\024\n\020CompressTypeGzip\020\001\022\024\n\020CompressTy" +
      "peZlib\020\002\022\026\n\022CompressTypeSnappy\020\003\022\023\n\017Comp" +
      "ressTypeLZ4\020\004:A\n\017service_timeout\022\037.googl" +
      "e.protobuf.ServiceOptions\030\240\234\001 \001(\003:\00510000" +
      ":8\n\016method_timeout\022\036.google.protobuf.Met" +
      "hodOptions\030\240\234\001 \001(\003:k\n\025request_compress_t" +
      "ype\022\036.google.protobuf.MethodOptions\030\241\234\001 ",
      "\001(\0162\030.sofa.pbrpc.CompressType:\020CompressT" +
      "ypeNone:l\n\026response_compress_type\022\036.goog" +
      "le.protobuf.MethodOptions\030\242\234\001 \001(\0162\030.sofa" +
      ".pbrpc.CompressType:\020CompressTypeNone"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          serviceTimeout.internalInit(descriptor.getExtensions().get(0));
          methodTimeout.internalInit(descriptor.getExtensions().get(1));
          requestCompressType.internalInit(descriptor.getExtensions().get(2));
          responseCompressType.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
