// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thirdparty/sofa/pbrpc/rpc_meta.proto

package sofa.pbrpc;

public final class SofaRpcMeta {
  private SofaRpcMeta() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RpcMetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .sofa.pbrpc.RpcMeta.Type type = 1;
    boolean hasType();
    sofa.pbrpc.SofaRpcMeta.RpcMeta.Type getType();
    
    // required uint64 sequence_id = 2;
    boolean hasSequenceId();
    long getSequenceId();
    
    // optional string method = 100;
    boolean hasMethod();
    String getMethod();
    
    // optional bool failed = 200;
    boolean hasFailed();
    boolean getFailed();
    
    // optional int32 error_code = 201;
    boolean hasErrorCode();
    int getErrorCode();
    
    // optional string reason = 202;
    boolean hasReason();
    String getReason();
    
    // optional .sofa.pbrpc.CompressType compress_type = 300;
    boolean hasCompressType();
    sofa.pbrpc.RpcOption.CompressType getCompressType();
    
    // optional .sofa.pbrpc.CompressType expected_response_compress_type = 301;
    boolean hasExpectedResponseCompressType();
    sofa.pbrpc.RpcOption.CompressType getExpectedResponseCompressType();
  }
  public static final class RpcMeta extends
      com.google.protobuf.GeneratedMessage
      implements RpcMetaOrBuilder {
    // Use RpcMeta.newBuilder() to construct.
    private RpcMeta(Builder builder) {
      super(builder);
    }
    private RpcMeta(boolean noInit) {}
    
    private static final RpcMeta defaultInstance;
    public static RpcMeta getDefaultInstance() {
      return defaultInstance;
    }
    
    public RpcMeta getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_sofa_pbrpc_RpcMeta_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_sofa_pbrpc_RpcMeta_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      REQUEST(0, 0),
      RESPONSE(1, 1),
      ;
      
      public static final int REQUEST_VALUE = 0;
      public static final int RESPONSE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sofa.pbrpc.SofaRpcMeta.RpcMeta.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        REQUEST, RESPONSE, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sofa.pbrpc.RpcMeta.Type)
    }
    
    private int bitField0_;
    // required .sofa.pbrpc.RpcMeta.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private sofa.pbrpc.SofaRpcMeta.RpcMeta.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public sofa.pbrpc.SofaRpcMeta.RpcMeta.Type getType() {
      return type_;
    }
    
    // required uint64 sequence_id = 2;
    public static final int SEQUENCE_ID_FIELD_NUMBER = 2;
    private long sequenceId_;
    public boolean hasSequenceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getSequenceId() {
      return sequenceId_;
    }
    
    // optional string method = 100;
    public static final int METHOD_FIELD_NUMBER = 100;
    private java.lang.Object method_;
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          method_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool failed = 200;
    public static final int FAILED_FIELD_NUMBER = 200;
    private boolean failed_;
    public boolean hasFailed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getFailed() {
      return failed_;
    }
    
    // optional int32 error_code = 201;
    public static final int ERROR_CODE_FIELD_NUMBER = 201;
    private int errorCode_;
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getErrorCode() {
      return errorCode_;
    }
    
    // optional string reason = 202;
    public static final int REASON_FIELD_NUMBER = 202;
    private java.lang.Object reason_;
    public boolean hasReason() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          reason_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .sofa.pbrpc.CompressType compress_type = 300;
    public static final int COMPRESS_TYPE_FIELD_NUMBER = 300;
    private sofa.pbrpc.RpcOption.CompressType compressType_;
    public boolean hasCompressType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public sofa.pbrpc.RpcOption.CompressType getCompressType() {
      return compressType_;
    }
    
    // optional .sofa.pbrpc.CompressType expected_response_compress_type = 301;
    public static final int EXPECTED_RESPONSE_COMPRESS_TYPE_FIELD_NUMBER = 301;
    private sofa.pbrpc.RpcOption.CompressType expectedResponseCompressType_;
    public boolean hasExpectedResponseCompressType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public sofa.pbrpc.RpcOption.CompressType getExpectedResponseCompressType() {
      return expectedResponseCompressType_;
    }
    
    private void initFields() {
      type_ = sofa.pbrpc.SofaRpcMeta.RpcMeta.Type.REQUEST;
      sequenceId_ = 0L;
      method_ = "";
      failed_ = false;
      errorCode_ = 0;
      reason_ = "";
      compressType_ = sofa.pbrpc.RpcOption.CompressType.CompressTypeNone;
      expectedResponseCompressType_ = sofa.pbrpc.RpcOption.CompressType.CompressTypeNone;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequenceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, sequenceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(100, getMethodBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(200, failed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(201, errorCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(202, getReasonBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(300, compressType_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(301, expectedResponseCompressType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, sequenceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(100, getMethodBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(200, failed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(201, errorCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(202, getReasonBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(300, compressType_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(301, expectedResponseCompressType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sofa.pbrpc.SofaRpcMeta.RpcMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sofa.pbrpc.SofaRpcMeta.RpcMeta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sofa.pbrpc.SofaRpcMeta.RpcMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_sofa_pbrpc_RpcMeta_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_sofa_pbrpc_RpcMeta_fieldAccessorTable;
      }
      
      // Construct using SofaRpcMeta.RpcMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = sofa.pbrpc.SofaRpcMeta.RpcMeta.Type.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        sequenceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        failed_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        reason_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        compressType_ = sofa.pbrpc.RpcOption.CompressType.CompressTypeNone;
        bitField0_ = (bitField0_ & ~0x00000040);
        expectedResponseCompressType_ = sofa.pbrpc.RpcOption.CompressType.CompressTypeNone;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sofa.pbrpc.SofaRpcMeta.RpcMeta.getDescriptor();
      }
      
      public sofa.pbrpc.SofaRpcMeta.RpcMeta getDefaultInstanceForType() {
        return getDefaultInstance();
      }
      
      public sofa.pbrpc.SofaRpcMeta.RpcMeta build() {
        sofa.pbrpc.SofaRpcMeta.RpcMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sofa.pbrpc.SofaRpcMeta.RpcMeta buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sofa.pbrpc.SofaRpcMeta.RpcMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sofa.pbrpc.SofaRpcMeta.RpcMeta buildPartial() {
        sofa.pbrpc.SofaRpcMeta.RpcMeta result = new sofa.pbrpc.SofaRpcMeta.RpcMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequenceId_ = sequenceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.failed_ = failed_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.reason_ = reason_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.compressType_ = compressType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.expectedResponseCompressType_ = expectedResponseCompressType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sofa.pbrpc.SofaRpcMeta.RpcMeta) {
          return mergeFrom((sofa.pbrpc.SofaRpcMeta.RpcMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sofa.pbrpc.SofaRpcMeta.RpcMeta other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSequenceId()) {
          setSequenceId(other.getSequenceId());
        }
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        if (other.hasFailed()) {
          setFailed(other.getFailed());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        if (other.hasCompressType()) {
          setCompressType(other.getCompressType());
        }
        if (other.hasExpectedResponseCompressType()) {
          setExpectedResponseCompressType(other.getExpectedResponseCompressType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSequenceId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              sofa.pbrpc.SofaRpcMeta.RpcMeta.Type value = sofa.pbrpc.SofaRpcMeta.RpcMeta.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sequenceId_ = input.readUInt64();
              break;
            }
            case 802: {
              bitField0_ |= 0x00000004;
              method_ = input.readBytes();
              break;
            }
            case 1600: {
              bitField0_ |= 0x00000008;
              failed_ = input.readBool();
              break;
            }
            case 1608: {
              bitField0_ |= 0x00000010;
              errorCode_ = input.readInt32();
              break;
            }
            case 1618: {
              bitField0_ |= 0x00000020;
              reason_ = input.readBytes();
              break;
            }
            case 2400: {
              int rawValue = input.readEnum();
              sofa.pbrpc.RpcOption.CompressType value = sofa.pbrpc.RpcOption.CompressType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(300, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                compressType_ = value;
              }
              break;
            }
            case 2408: {
              int rawValue = input.readEnum();
              sofa.pbrpc.RpcOption.CompressType value = sofa.pbrpc.RpcOption.CompressType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(301, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                expectedResponseCompressType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .sofa.pbrpc.RpcMeta.Type type = 1;
      private sofa.pbrpc.SofaRpcMeta.RpcMeta.Type type_ = sofa.pbrpc.SofaRpcMeta.RpcMeta.Type.REQUEST;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public sofa.pbrpc.SofaRpcMeta.RpcMeta.Type getType() {
        return type_;
      }
      public Builder setType(sofa.pbrpc.SofaRpcMeta.RpcMeta.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = sofa.pbrpc.SofaRpcMeta.RpcMeta.Type.REQUEST;
        onChanged();
        return this;
      }
      
      // required uint64 sequence_id = 2;
      private long sequenceId_ ;
      public boolean hasSequenceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getSequenceId() {
        return sequenceId_;
      }
      public Builder setSequenceId(long value) {
        bitField0_ |= 0x00000002;
        sequenceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSequenceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequenceId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string method = 100;
      private java.lang.Object method_ = "";
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMethod(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        method_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000004);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      void setMethod(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        method_ = value;
        onChanged();
      }
      
      // optional bool failed = 200;
      private boolean failed_ ;
      public boolean hasFailed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getFailed() {
        return failed_;
      }
      public Builder setFailed(boolean value) {
        bitField0_ |= 0x00000008;
        failed_ = value;
        onChanged();
        return this;
      }
      public Builder clearFailed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        failed_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 error_code = 201;
      private int errorCode_ ;
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getErrorCode() {
        return errorCode_;
      }
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000010;
        errorCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errorCode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string reason = 202;
      private java.lang.Object reason_ = "";
      public boolean hasReason() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReason(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        reason_ = value;
        onChanged();
        return this;
      }
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000020);
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      void setReason(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        reason_ = value;
        onChanged();
      }
      
      // optional .sofa.pbrpc.CompressType compress_type = 300;
      private sofa.pbrpc.RpcOption.CompressType compressType_ = sofa.pbrpc.RpcOption.CompressType.CompressTypeNone;
      public boolean hasCompressType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public sofa.pbrpc.RpcOption.CompressType getCompressType() {
        return compressType_;
      }
      public Builder setCompressType(sofa.pbrpc.RpcOption.CompressType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        compressType_ = value;
        onChanged();
        return this;
      }
      public Builder clearCompressType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        compressType_ = sofa.pbrpc.RpcOption.CompressType.CompressTypeNone;
        onChanged();
        return this;
      }
      
      // optional .sofa.pbrpc.CompressType expected_response_compress_type = 301;
      private sofa.pbrpc.RpcOption.CompressType expectedResponseCompressType_ = sofa.pbrpc.RpcOption.CompressType.CompressTypeNone;
      public boolean hasExpectedResponseCompressType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public sofa.pbrpc.RpcOption.CompressType getExpectedResponseCompressType() {
        return expectedResponseCompressType_;
      }
      public Builder setExpectedResponseCompressType(sofa.pbrpc.RpcOption.CompressType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        expectedResponseCompressType_ = value;
        onChanged();
        return this;
      }
      public Builder clearExpectedResponseCompressType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        expectedResponseCompressType_ = sofa.pbrpc.RpcOption.CompressType.CompressTypeNone;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sofa.pbrpc.RpcMeta)
    }
    
    static {
      defaultInstance = new RpcMeta(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sofa.pbrpc.RpcMeta)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sofa_pbrpc_RpcMeta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sofa_pbrpc_RpcMeta_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$thirdparty/sofa/pbrpc/rpc_meta.proto\022\n" +
      "sofa.pbrpc\032&thirdparty/sofa/pbrpc/rpc_op" +
      "tion.proto\"\246\002\n\007RpcMeta\022&\n\004type\030\001 \002(\0162\030.s" +
      "ofa.pbrpc.RpcMeta.Type\022\023\n\013sequence_id\030\002 " +
      "\002(\004\022\016\n\006method\030d \001(\t\022\017\n\006failed\030\310\001 \001(\010\022\023\n\n" +
      "error_code\030\311\001 \001(\005\022\017\n\006reason\030\312\001 \001(\t\0220\n\rco" +
      "mpress_type\030\254\002 \001(\0162\030.sofa.pbrpc.Compress" +
      "Type\022B\n\037expected_response_compress_type\030" +
      "\255\002 \001(\0162\030.sofa.pbrpc.CompressType\"!\n\004Type" +
      "\022\013\n\007REQUEST\020\000\022\014\n\010RESPONSE\020\001B\rB\013SofaRpcMe",
      "ta"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sofa_pbrpc_RpcMeta_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sofa_pbrpc_RpcMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sofa_pbrpc_RpcMeta_descriptor,
              new java.lang.String[] { "Type", "SequenceId", "Method", "Failed", "ErrorCode", "Reason", "CompressType", "ExpectedResponseCompressType", },
              sofa.pbrpc.SofaRpcMeta.RpcMeta.class,
              sofa.pbrpc.SofaRpcMeta.RpcMeta.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sofa.pbrpc.RpcOption.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
